### ISSUE TITLE
Используй const вместо let

### ISSUE THREAD

**Issue by codyfet** [varandej/react-20-02-19#2]
https://github.com/varandej/react-20-02-19/blob/31fac2c97e2dcd1ee80a3c128f7e1ae99d33f371/src/components/reusable-component.jsx#L46

Здесь переменная нигде не переопределяется, поэтмоу смысла использовать let нет никакого.
let вообще очень редко используется, поэтому по умолчанию используй всегда const, а в ситуации когда нужно let тебе IDE сама подскажет

**Comment by varandej** [comment]
Готово
