### ISSUE TITLE
&& лучше не злоупотреблять

### ISSUE THREAD

**Issue by codyfet** [varandej/react-20-02-19#3]
https://github.com/varandej/react-20-02-19/blob/31fac2c97e2dcd1ee80a3c128f7e1ae99d33f371/src/components/reusable-component.jsx#L40

Используй такой синтаксис в render, а во всяких методах лучше писать классический if (оно более читабельно)

```
if (this.state.inputValue.length > 0) {
        this.setState({
            showFields: true
        });
}
```

**Comment by varandej** [comment]
Готово
