### ISSUE TITLE
Избыточная перменная в стейте showFields

### ISSUE THREAD

**Issue by codyfet** [varandej/react-20-02-19#4]
https://github.com/varandej/react-20-02-19/blob/31fac2c97e2dcd1ee80a3c128f7e1ae99d33f371/src/components/reusable-component.jsx#L77

showFields хранить в стейте ни к чему. Нужно стремитсья к тому, чтобы было как можно меньше лишних переменных в стейте. и как следствие - проще логика. Условие отображения панели можно вычислить на основании objectArr.arr.length

прямо в рендере проверяй, тогда и переменная showFields  твоя не нужна будет: 

```
 {objectArr.arr.length > 0 && (
                <div className='dataFields'>
                    <ListGroup>
                        {arr.map((item) => {
                            return (
                                   <DataFields object={item} className='changebleClass' value= 
                                             {this.state.inputValue}
                                    />
                           );
                        })}
                    </ListGroup>
                </div>
   )}
```

примерно так. И многострочную верстку лучше в () оборачивать как я обернул выше (обрати внимание)

**Comment by varandej** [comment]
На неё привязан onBlur элемента Input, который скрывает выпадающий список. Если в рендере использовать массив результатов поиска как условие, то на снятии фокусировки с Input придется этот массив затирать, чтобы спрятать список, и при повторном фокусе снова делать запрос с введенным значением, чтобы снова его вывести. Получится не очень логично.
Как в таком случае лучше поступить?

`onBlur={this.handleInputBlur}`

`handleInputBlur() {
        this.setState({
            showFields: false
        })
    }`

`onFocus={this.handleInputFocus}`

`handleInputFocus() {
    if (this.state.inputValue.length > 0) {
        this.setState({
            showFields: true
        });
    }
}`
